### PR TITLE
chore: Add Nextcloud 26 support

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by gary-kim — APPROVED** [review]

**Comment by nickvergessen** [comment]
Can you release @gary-kim  ?

**Comment by gary-kim** [comment]
:+1:

**Comment by nickvergessen** [comment]
Ah, you release 1.26.0-0 but the - makes it a unstable version.
Can you release 1.26.0 for now while I escalate the appstore fix

**Comment by gary-kim** [comment]
Ah, I see. Yup, I'll release 1.26.0

**Pull request merged**
